mode: json
json_timestamp: epoch_s
binary_struct: "!QddffffH"
fields:
  vehicle_id: id
  ts: time
  lat: lat
  lon: lon
  speed: speed
  heading: heading
  route_id: route
  direction_id: dir
  trip_id: trip
binary_index_map:
  vehicle_id: 0
  ts: 1
  lat: 2
  lon: 3
  speed: 4
  heading: 5
  route_id: null
  direction_id: null
  trip_id: null
